### ISSUE TITLE
Tutorial examples segfault on Linux

### ISSUE THREAD

**Issue by SigmaX** [UCI-CARL/CARLsim5#7]
Running with no GPU.
OS: Arch Linux and Ubuntu 20.04 (have tried both)
Compiler: GCC 10.2.0

## Steps to reproduce

 * `make release_nocuda`
 * `make install`
 * `cd doc/source/tutorial/1_basic_concepts`
 * `g++ -I/home/eric/CARL/include -L/home/eric/CARL/lib -pthread -Wno-deprecated-gpu-targets  src/main_basic_concepts.cpp -o basic_concepts -lcarlsim`
 * `./basic_concepts`

## Expected Behavior

The model will run to completion.

## Observed behavior

Segfault when the model reaches the "running" phase:

```
[eric@alfred 1_basic_concepts]$ ./basic_concepts 
*********************************************************************************
********************      Welcome to CARLsim 4.0      ***************************
*********************************************************************************

***************************** Configuring Network ********************************
Starting CARLsim simulation "basics" in USER mode
Random number seed: 1603206565
Running COBA mode:
  - AMPA decay time            =     5 ms
  - NMDA rise time (disabled)  =     0 ms
  - GABAa decay time           =     6 ms
  - GABAb rise time (disabled) =     0 ms
  - GABAb decay time           =   150 ms


************************** Global Network Configuration *******************************
The number of neurons in the network (numN) = 2
The number of regular neurons in the network (numNReg:numNExcReg:numNInhReg) = 1:1:0
The number of poisson neurons in the network (numNPois:numNExcPois:numInhPois) = 1:1:0
The maximum axonal delay in the network (maxDelay) = 1

+ Local Network (0)
|-+ Group List:
  |-+ Local Group input(G:0,L:1): 
    |- Type                       =    EXCIT
    |- Num of Neurons             =        1
    |- Start Id                   = (G:1,L:1)
    |- End Id                     = (G:1,L:1)
    |- numPostSynapses            =        1
    |- numPreSynapses             =        0
    |- Refractory period          =  0.00000
  |-+ Local Group output(G:1,L:0): 
    |- Type                       =    EXCIT
    |- Num of Neurons             =        1
    |- Start Id                   = (G:0,L:0)
    |- End Id                     = (G:0,L:0)
    |- numPostSynapses            =        0
    |- numPreSynapses             =        1
|-+ Connection List:
  |-+ Local Connection Id 0: input(0) => output(1)
    |- Type                       =    FIXED
    |- Min weight                 =  0.00000
    |- Max weight                 =  0.10000
    |- Initial weight             =  0.10000
    |- Min delay                  =        1
    |- Max delay                  =        1
    |- Radius X                   =    -1.00
    |- Radius Y                   =    -1.00
    |- Radius Z                   =    -1.00
    |- Num of synapses            = 1
    |- Avg numPreSynapses         =     1.00
    |- Avg numPostSynapses        =     1.00

*****************      Initializing CPU 0 Runtime      *************************
SpikeMonitor set for group 1 (output)

******************** Running the simulation on 0 GPU(s) and 1 CPU(s) ***************************

Segmentation fault (core dumped)
```

**Comment by SigmaX** [comment]
PS: this works fine for my on macOS, but not on my Arch box.

**Comment by SigmaX** [comment]
Recompiled with the `DEVELOPER` log setting (instead of `USER`).  Doesn't seem to yield much more information:

```
[eric@alfred 1_basic_concepts]$ ./basic_concepts 
*********************************************************************************
********************      Welcome to CARLsim 4.0      ***************************
*********************************************************************************

***************************** Configuring Network ********************************
Starting CARLsim simulation "basics" in DEVELOPER mode
Random number seed: 1603210586
[DEBUG carlsim/kernel/src/snn_manager.cpp:2114] Current local time and date: Tue Oct 20 12:16:26 2020

[DEBUG carlsim/kernel/src/snn_manager.cpp:166] CONNECT SETUP: connId=0, mulFast=1.000000, mulSlow=1.000000
Running COBA mode:
  - AMPA decay time            =     5 ms
  - NMDA rise time (disabled)  =     0 ms
  - GABAa decay time           =     6 ms
  - GABAb rise time (disabled) =     0 ms
  - GABAb decay time           =   150 ms
[DEBUG carlsim/kernel/src/snn_manager.cpp:3553] Beginning compilation of the network....
[DEBUG carlsim/kernel/src/snn_manager.cpp:2942] Allocation for 1(output), St=0, End=0
[DEBUG carlsim/kernel/src/snn_manager.cpp:2942] Allocation for 0(input), St=1, End=1


************************** Global Network Configuration *******************************
The number of neurons in the network (numN) = 2
The number of regular neurons in the network (numNReg:numNExcReg:numNInhReg) = 1:1:0
The number of poisson neurons in the network (numNPois:numNExcPois:numInhPois) = 1:1:0
The maximum axonal delay in the network (maxDelay) = 1
[DEBUG carlsim/kernel/src/snn_manager.cpp:2961] Allocation for group (output) [id:1, local id:0], St=0, End=0
[DEBUG carlsim/kernel/src/snn_manager.cpp:2961] Allocation for group (input) [id:0, local id:1], St=1, End=1

+ Local Network (0)
|-+ Group List:
  |-+ Local Group input(G:0,L:1): 
    |- Type                       =    EXCIT
    |- Num of Neurons             =        1
    |- Start Id                   = (G:1,L:1)
    |- End Id                     = (G:1,L:1)
    |- numPostSynapses            =        1
    |- numPreSynapses             =        0
    |- Refractory period          =  0.00000
  |-+ Local Group output(G:1,L:0): 
    |- Type                       =    EXCIT
    |- Num of Neurons             =        1
    |- Start Id                   = (G:0,L:0)
    |- End Id                     = (G:0,L:0)
    |- numPostSynapses            =        0
    |- numPreSynapses             =        1
|-+ Connection List:
  |-+ Local Connection Id 0: input(0) => output(1)
    |- Type                       =    FIXED
    |- Min weight                 =  0.00000
    |- Max weight                 =  0.10000
    |- Initial weight             =  0.10000
    |- Min delay                  =        1
    |- Max delay                  =        1
    |- Radius X                   =    -1.00
    |- Radius Y                   =    -1.00
    |- Radius Z                   =    -1.00
    |- Num of synapses            = 1
    |- Avg numPreSynapses         =     1.00
    |- Avg numPostSynapses        =     1.00

*****************      Initializing CPU 0 Runtime      *************************
[DEBUG carlsim/kernel/src/snn_cpu_module.cpp:1984] copyExternalCurrent: lGrpId=-1, ptrPos=0, length=1, allocate=y
[DEBUG carlsim/kernel/src/snn_cpu_module.cpp:1417] Transfering group settings to CPU:
[DEBUG carlsim/kernel/src/snn_cpu_module.cpp:1419] Settings for Group output:
[DEBUG carlsim/kernel/src/snn_cpu_module.cpp:1421]      Type: 6
[DEBUG carlsim/kernel/src/snn_cpu_module.cpp:1422]      NumN: 1
[DEBUG carlsim/kernel/src/snn_cpu_module.cpp:1423]      M: 0
[DEBUG carlsim/kernel/src/snn_cpu_module.cpp:1424]      PreM: 1
[DEBUG carlsim/kernel/src/snn_cpu_module.cpp:1425]      spikeGenerator: 0
[DEBUG carlsim/kernel/src/snn_cpu_module.cpp:1426]      FixedInputWts: 1
[DEBUG carlsim/kernel/src/snn_cpu_module.cpp:1427]      MaxDelay: 1
[DEBUG carlsim/kernel/src/snn_cpu_module.cpp:1428]      WithSTDP: 0
[DEBUG carlsim/kernel/src/snn_cpu_module.cpp:1445]      WithSTP: 0
[DEBUG carlsim/kernel/src/snn_cpu_module.cpp:1451]      spikeGen: is not set 
[DEBUG carlsim/kernel/src/snn_cpu_module.cpp:1419] Settings for Group input:
[DEBUG carlsim/kernel/src/snn_cpu_module.cpp:1421]      Type: 7
[DEBUG carlsim/kernel/src/snn_cpu_module.cpp:1422]      NumN: 1
[DEBUG carlsim/kernel/src/snn_cpu_module.cpp:1423]      M: 1
[DEBUG carlsim/kernel/src/snn_cpu_module.cpp:1424]      PreM: 0
[DEBUG carlsim/kernel/src/snn_cpu_module.cpp:1425]      spikeGenerator: 1
[DEBUG carlsim/kernel/src/snn_cpu_module.cpp:1426]      FixedInputWts: 1
[DEBUG carlsim/kernel/src/snn_cpu_module.cpp:1427]      MaxDelay: 1
[DEBUG carlsim/kernel/src/snn_cpu_module.cpp:1428]      WithSTDP: 0
[DEBUG carlsim/kernel/src/snn_cpu_module.cpp:1445]      WithSTP: 0
[DEBUG carlsim/kernel/src/snn_cpu_module.cpp:1451]      spikeGen: is not set 
SpikeMonitor set for group 1 (output)
[DEBUG carlsim/kernel/src/snn_manager.cpp:798] runNetwork: runDur=1000ms, printRunSummary=y

******************** Running the simulation on 0 GPU(s) and 1 CPU(s) ***************************

Segmentation fault (core dumped)
```

**Comment by SigmaX** [comment]
A little `cout` debugging narrows the problem down to `SNN:resetSpikeCnt` in `snn_manager.cpp`, where it iterates through `groupPartitionLists`.  The error seems to be non-deterministic, sometimes failing on the second or third iteration through the loop, sometimes making it more than a dozen times through.

The same `pthreads` code here is copy and pasted around a dozen times throughout the file, however, so if it's a race condition, there may be lots of them.

**Comment by SigmaX** [comment]
Tossed CARLsim into a few VMS, and can confirm that the same segfault occurs with Ubuntu 20.04

**Comment by SigmaX** [comment]
Jinwei reports that these work on Ubuntu 16.04 and 18.04, but not 20.04.  GCC version doesn't seem to be the root cause: 18.04 with GCC 7.5 succeeds, but 20.04 with GCC 5, 7, or 9 all fail.

**Comment by SigmaX** [comment]
After recompiling `libcarlsim.a` and tutorial 1 with `-g` and running it in `gdb`, I've narrowed down the line that triggers the segfault to **line 1337 of `snn_cpu_module.cpp`**.

![image](https://user-images.githubusercontent.com/313154/97117347-74e7e180-16d9-11eb-8158-1d9913a18abd.png)

This function is called by a thread that gets launched by `SNN::resetSpikeCnt()` on line 6090 of `snn_manager.cpp`.

This is **Linux-only** code (activated via `#if defined` blocks) that only gets triggerd in **CPU mode**, which could explain why we think some people had no problem on Ubuntu 20.04 (they may have been running in GPU mode).

**Comment by KarlXing** [comment]
The problem is probably caused by upgraded c/c++ libraries. CARLsim can work on Ubuntu 20.04 once we downgrade the make version to 4.1 and gcc/g++ to 7.5. I will do more tests to figure out what version configuration we could support.

**Comment by SigmaX** [comment]
I've discovered that the segfault **disappears** if I compile without `-O3`.

With `-O3`, I can set breakpoints with with `gdb` during initialization of the network and follow it through the following function calls:

```
    SNN::runNetwork --> SNN::resetSpkCnt --> SNN::helperResetSpikeCnt_CPU --> SNN::resetSpikeCnt_CPU
```

It's when I step through `SNN::resetSpikeCnt_CPU` that I see the segfault---but somehow `gdb` leaps straight from there to line `1337` as indicated above.  This doesn't make sense (`SNN::shiftSpikeTables_CPU` is called much later in the program than `SNN::resetSpikeCnt_CPU`).

I was thinking `gdb` might be [confused because it was compiled with `-O3` ](https://stackoverflow.com/questions/41565105/gdb-breakpoint-gets-hit-in-the-wrong-line-number)(which I understand can mess up line number information for debugging?).

That's when I recomipled with `-O0`, and found no segfault at all.

No sense of why.  But I see people [have](https://stackoverflow.com/questions/31373765/determine-cause-of-segfault-when-using-o3) had [problems](https://github.com/samtools/htslib/issues/400) with `-O3` causing segfaults in past versions of GCC---often connected to vectorization with SSE (which is enabled by `-O3`).

**Comment by SigmaX** [comment]
Confirmed that removing `-O3` is a successful workaround on both Arch Linux and Ubuntu 20.04.

**Comment by SigmaX** [comment]
Leaving the issue open, though, since removing the `-O3` optimization is not acceptable as a long-term solution.

**Comment by nmsutton** [comment]
@SigmaX I had the same issue (as mentioned in my [issue 14](https://github.com/UCI-CARL/CARLsim5/issues/14)) and unfortunately changing `prep_release:
	$(eval CXXFL += -O3 -ffast-math)` to `prep_release:
	$(eval CXXFL += --O0 -ffast-math)` still caused the seg fault. I am using Ubuntu 21.10 (preview build).

**Comment by SigmaX** [comment]
@nmsutton Sorry to hear that it wasn't as simple for you.  I saw that you found a solution for your compute-capability problem in the other issue—but do I understand that downgrading to GCC 7.5 was enough to circumvent this issue in your case?

I'm no macOS all this week, but hope to look a this a bit over the holidays when I'm back at a Linux box.

**Comment by nmsutton** [comment]
@SigmaX thanks for the follow-up. I was never able to get CARLsim5 examples/tests fully working but worked with Lars and Killian to get CARLsim6 working successfully on my GPU. One issue suspected is that my GPU has a compute capacity of 8.6 and does not appear backward compatible if an earlier settings is used. For example, if in compiling the code, the compute capacity 5 flag is used in addition to 8.6 then that may cause several issues. Setting the code to compile with the compute capacity and sm setting that exactly matches the GPU and no other compute capacity flags can help it to work (different than what currently exists in CARLsim5 code that just sets a low compute capacity setting and assumes many cards generally support it). E.g., "-gencode arch=compute_86,code=sm_86".

As Killian mentioned in the meeting today, a possible solution is just to tell people with newer GPUs to use CARLsim6 because such GPU-specific settings are planned to be configurable and better documented in it. I've not tried backporting some changes such as that which are in CARLsim6 into CARLsim5 to get compatibility but perhaps it would work. I appreciate your offer to look at this over the holidays but it is a very low priority since CARLsim6 is working well with my GPU. I plan to focus on CARLsim6 because that is a working solution without putting further dev work into this.

**Comment by SigmaX** [comment]
@nmsutton Glad to hear it!

I agree that CARLsim6 is the priority, including for fixes to support newer hardware like this.  So I'll go ahead and close this issue.
